"""lineage.py - kinship queries over the journal (read-only views).

PARENT = a reference image. CHILD = an image that used this one as input.
SIBLINGS = images generated by an IDENTICAL config MODULO SEED (recipe
minus seed, plus the parent id list). Imports are singleton sibling sets.
One journal (2026-08-25): every edge resolves.
"""
import json


def sibling_key(rec):
    r = rec.get("recipe")
    if not r:
        return ("import", rec["id"])
    r = dict(r)
    r.pop("seed", None)
    return (tuple(sorted(rec.get("parents") or [])), json.dumps(r, sort_keys=True))


def family(store, i):
    """Parents / siblings / children of ONE image (the Genealogy sheets,
    anchored to the WI). Flat, id-ordered, alive only (archived included -
    views show everything). None if the id is unknown."""
    with store.lock:
        rec = store.images.get(i)
        if not rec:
            return None
        key = sibling_key(rec)
        alive = store.alive
        return {
            "id": i,
            "parents": [{"id": p} for p in (rec.get("parents") or []) if alive(p)],
            "siblings": [{"id": j} for j, r in sorted(store.images.items())
                         if alive(j) and sibling_key(r) == key],
            "children": [{"id": j} for j, r in sorted(store.images.items())
                         if alive(j) and i in (r.get("parents") or [])]}
