"""lineage.py - kinship queries over the journal (read-only views).

PARENT = a reference image. CHILD = an image that used this one as input.
SIBLINGS = images generated by an IDENTICAL config MODULO SEED (recipe
minus seed, plus the parent id list). Imports are singleton sibling sets.
The journal is project-local; a cross-project parent is simply unknowable.
"""
import json

from project import parse_image_ref, root


def sibling_key(rec):
    r = rec.get("recipe")
    if not r:
        return ("import", rec["id"])
    r = dict(r)
    r.pop("seed", None)
    return (tuple(sorted(rec.get("parents") or [])), json.dumps(r, sort_keys=True))


def family(store, i):
    """Parents / siblings / children of ONE image (the Genealogy sheets,
    anchored to the WI). Flat, id-ordered, alive only - archived images
    vanish, no placeholders. None if the id is unknown."""
    with store.lock:
        rec = store.images.get(i)
        if not rec:
            return None
        key = sibling_key(rec)
        alive = store.alive
        return {
            "id": i,
            "parents": [{"id": p} for p in (rec.get("parents") or []) if alive(p)],
            "siblings": [{"id": j} for j, r in sorted(store.images.items())
                         if alive(j) and sibling_key(r) == key],
            "children": [{"id": j} for j, r in sorted(store.images.items())
                         if alive(j) and i in (r.get("parents") or [])]}


def foreign_meta(rel):
    """Metadata for an image in ANOTHER project (asset datasets span
    projects): read that project's journal for the record. Read-only; no
    gc verdict - that is the other project's business when it is open."""
    ref = parse_image_ref(rel)
    if not ref:
        return None
    proj, i = ref
    j = root() / proj / "journal.jsonl"
    rec, gone = None, False
    if j.exists():
        for line in j.read_text(encoding="utf-8").splitlines():
            if not line.strip():
                continue
            ev = json.loads(line)
            if ev.get("t") == "image" and ev.get("id") == i:
                rec = ev
            elif ev.get("t") == "gc" and i in ev.get("ids", []):
                gone = True
    if rec is None:
        return None
    return {"id": i, "w": rec.get("w"), "h": rec.get("h"), "source": rec.get("source"),
            "ts": rec.get("ts"), "recipe": rec.get("recipe"),
            "parents": rec.get("parents"), "gone": gone,
            "gc": "archived" if gone else f"in project {proj}",
            "path": str(root() / proj / "images" / f"{i}.png")}
